SkiRentalShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
from django.contrib.auth import views as auth_views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name="basket_add"),
    path('delete/', views.basket_delete, name="basket_delete"),
    path('update/', views.basket_update, name="basket_update"),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class Category(models.Model):  # skis, snowboard, boots, poles, goggles
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])


class Brand(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='product_creator', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default/default.jpg')
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])


class Size(models.Model):
    product = models.ForeignKey(Product, related_name='size', on_delete=models.CASCADE)
    size = models.IntegerField()

    def __str__(self):
        return self.size

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def all_products(request):
    products = Product.objects.all()
    return render(request, 'store/home.html', {'products': products})


def categories(request):
    categories = Category.objects.all()
    return {'categories': categories}


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    return render(request, 'store/details.html', {'product' : product})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/category.html', {'category' : category, 'products' : products})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Ski Rental{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static "css/optimised2.css" %}" rel="stylesheet">
    <link rel="icon" href="{% static "logo/logo.png" %} ">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript">
        window.CSRF_TOKEN = "{{ csrf_token }}";
        url_add = "{% url "basket:basket_add" %}";
        url_del = "{% url "basket:basket_delete" %}";
        url_upd = "{% url "basket:basket_update" %}";
    </script>
    <script src="{% static "js/details.js" %}"></script>
</head>
<body>
<header>
    <nav>
        <div class="dropdown-icon">
            <button class="dropdown-button"><i class="fa fa-bars"></i></button>
        </div>
        <div class="nav-left">
            <div class="nav-collapsible">
                <a href="/"><img src="{% static "logo/logo.png" %}" alt="Ski Rental"/></a>
            </div>
            <div class="dropdown nav-collapsible">
                <button class="dropbtn">Shop</button>
                <ul class="dropdown-content">
                    <li><a class="nav-left-a" href="{% url "store:all_products" %}">All</a></li>
                    {% for c in categories %}
                        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                            <a class="nav-left-a" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div id="basket-nav" class="nav-collapsible">
                <a href="{% url "basket:basket_summary" %}">
                    {% with total_qty=basket|length %}
                        <div id="basket-qty"
                             style="float: left; margin: 18px 0 18px 18px;color: black;font-size: 20px;">
                        {% if total_qty > 0 %}
                            {{ total_qty }}
                        {% else %}
                            0
                        {% endif %}

                    {% endwith %}
                    </div>
                    <i href="/" class="fa fa-shopping-cart" style="font-size:30px"></i>
                </a>
            </div>
        </div>
        <div class="nav-right">
        <div>
            {% if user.is_authenticated %}
                <a type="button" role="button" href="{% url "account:logout" %}?next={% url "account:login" %}">
                    <i class="fa fa-sign-out" style="font-size: 30px"></i>
                </a>
                <a type="button" role="button" href="{% url "account:dashboard" %}">
                    <i class="fa fa-user" style="font-size: 30px"></i>
                </a>
            {% else %}
                <a type="button" role="button" href="{% url "account:login" %}">
                    <i class="fa fa-sign-in" style="font-size: 30px"></i>
                </a>
            {% endif %}
        </div>
            <div class="nav-collapsible">
                <form class="search-form">
                    <label>
                        <input class="search-input" type="search" placeholder="Search"/>
                    </label>
                    <button class="submit-button" type="submit"><span class="fa fa-search"></span></button>
                </form>
            </div>
        </div>

    </nav>
</header>
<div id="greeting">{% block greeting %}{% endblock %}</div>
<div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

templates/store/category.html
{% extends "./home.html" %}
{% load static %}
{% block title %} {{ category.name|title }} {% endblock %}

templates/store/details.html
{% extends "./base.html" %}

{% block content %}
    <main>
        <div class="detail-grid">
            <div class="item">
                <img src="{{ product.image.url }}" alt="no image found"/>
            </div>
            <div class="item">
                <div class="description-price-grid">
                    <div class="description item">
                        <p class="item-text" style="font-size: 30px">
                            <a>{{ product.brand }} {{ product.name }}</a>
                        </p>
                        <div>
                            <small class="text-muted">{{ product.description|truncatechars:1500 }}</small>
                        </div>
                    </div>
                </div>
                <div class="cart-info">
                    <div class="add-to-cart-container">
                        <button class="add-to-cart-button" id="add-button" value="{{ product.id }}">
                            <i class="fa fa-shopping-cart"></i> Add to Cart
                        </button>
                        <div class="price">{{ product.price }}</div>
                    </div>
                    <div class="quantity">
                        <label for="select">Qty</label>
                        <select id="select">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    <main>

        <div class="lead">
            <div>
                <div class="lead title">
                    <h1>Rent, Ski, Have Fun</h1>
                    <p class="lead text-muted">We're a small ski rent company with the aim
                        to enable every willing person to go skiing</p>
                    <p>
                        <a href="{% url "account:register" %}">Make an account</a>
                    </p>
                </div>
            </div>
        </div>


        <div class="container">
            {% for product in products %}

                <div class="item">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}">
                    </a>
                    <div class="description">
                        <p class="item-text">
                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                        </p>
                        <div>
                            <small class="text-muted">{{ product.description|truncatechars:255 }}</small>
                        </div>
                    </div>
                </div>

            {% endfor %}

        </div>


    </main>
{% endblock %}